# Generated by Django 5.0 on 2023-12-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('fatherName', models.CharField(max_length=30)),
                ('address', models.TextField()),
            ],
        ),
    ]
