# Generated by Django 5.0 on 2024-01-05 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carBrand', '0001_initial'),
        ('carModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='carBrand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carBrand.carbrand'),
        ),
    ]
