# Generated by Django 5.0 on 2024-01-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carModel', '0005_carmodel_quantity_alter_carmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='description',
            field=models.TextField(default='This car'),
        ),
    ]
