# Generated by Django 5.0 on 2023-12-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('auto_field', models.AutoField(primary_key=True, serialize=False)),
                ('binary_field', models.BinaryField()),
                ('boolean_field', models.BooleanField()),
                ('char_field', models.CharField(max_length=255)),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=5)),
                ('email_field', models.EmailField(max_length=254)),
                ('float_field', models.FloatField()),
                ('big_integer_field', models.BigIntegerField()),
                ('date_field', models.DateField()),
                ('duration_field', models.DurationField()),
            ],
        ),
    ]
